# Generated by Django 6.0.4 on 2026-04-15 06:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11, verbose_name='余额')),
                ('is_complete', models.BooleanField(default=False, verbose_name='是否完成')),
                ('remarks', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '总账本',
                'verbose_name_plural': '总账本',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11, verbose_name='预算金额')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11, verbose_name='实际金额')),
                ('is_complete', models.BooleanField(default=False, verbose_name='是否完成')),
                ('star', models.PositiveIntegerField(default=0, verbose_name='满意度')),
                ('remarks', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='finance.ledger', verbose_name='所属总账')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateField(verbose_name='交易日期')),
                ('partner', models.CharField(max_length=100, verbose_name='交易对象')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='金额')),
                ('star', models.PositiveIntegerField(default=0, verbose_name='满意度')),
                ('channel', models.CharField(blank=True, max_length=100, verbose_name='交易渠道')),
                ('detail', models.CharField(blank=True, max_length=100, verbose_name='交易细节')),
                ('ticket_file', models.FileField(blank=True, upload_to='tickets/%Y/%m/', verbose_name='凭据')),
                ('remarks', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'ordering': ['-trade_time', '-created_at'],
            },
        ),
    ]
