# Generated by Django 6.0.4 on 2026-04-17 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '消费计划', 'verbose_name_plural': '消费计划'},
        ),
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ['-created_at'], 'verbose_name': '账本', 'verbose_name_plural': '账本'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='ledger',
        ),
        migrations.AddField(
            model_name='category',
            name='category_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_categories', to='finance.ledger', verbose_name='关联分类账本'),
        ),
        migrations.AddField(
            model_name='category',
            name='time_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_categories', to='finance.ledger', verbose_name='关联时间账本'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='ledger_type',
            field=models.CharField(choices=[('time', '时间维度'), ('category', '分类维度')], default='time', max_length=20, verbose_name='账本类型'),
        ),
    ]
