# Generated by Django 6.0.4 on 2026-07-05 06:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_category_category_ledger_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('bank', '银行账户'), ('securities', '证券账户'), ('cash', '现金'), ('credit', '信用卡'), ('alipay', '支付宝')], max_length=20, verbose_name='账户类型')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11, verbose_name='初始余额')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=11, verbose_name='当前余额')),
                ('remarks', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户',
                'ordering': ['account_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.account', verbose_name='关联账户'),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='金额')),
                ('trade_time', models.DateField(verbose_name='转账日期')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='finance.account', verbose_name='转出账户')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='finance.account', verbose_name='转入账户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '转账记录',
                'verbose_name_plural': '转账记录',
                'ordering': ['-trade_time', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_account', models.F('to_account')), _negated=True), name='transfer_accounts_differ')],
            },
        ),
    ]
