# Generated by Django 6.0.4 on 2026-07-05 08:04

import django.db.models.deletion
from django.db import migrations, models


SEED_TYPES = [
    ("银行账户", "bank", 1),
    ("证券账户", "securities", 2),
    ("现金", "cash", 3),
    ("信用卡", "credit", 4),
    ("支付宝", "alipay", 5),
]


def seed_account_types(apps, schema_editor):
    AccountType = apps.get_model("finance", "AccountType")
    for name, slug, order in SEED_TYPES:
        AccountType.objects.get_or_create(
            slug=slug, defaults={"name": name, "sort_order": order}
        )


def map_account_types(apps, schema_editor):
    Account = apps.get_model("finance", "Account")
    AccountType = apps.get_model("finance", "AccountType")
    type_map = {at.slug: at for at in AccountType.objects.all()}

    for account in Account.objects.all():
        # account_type field was renamed to _old_type via RenameField
        old_slug = getattr(account, "_old_type", None)
        if old_slug and old_slug in type_map:
            account.account_type = type_map[old_slug]
            account.save(update_fields=["account_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_account_transaction_account_transfer"),
    ]

    operations = [
        # 1. Create AccountType table
        migrations.CreateModel(
            name="AccountType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30, verbose_name="类型名称")),
                ("slug", models.CharField(max_length=30, unique=True, verbose_name="标识")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "账户类型",
                "verbose_name_plural": "账户类型",
                "ordering": ["sort_order", "name"],
            },
        ),
        # 2. Seed the 5 built-in types
        migrations.RunPython(seed_account_types, reverse_code=migrations.RunPython.noop),
        # 3. Rename old CharField column so FK can reuse the name
        migrations.RenameField(
            model_name="account",
            old_name="account_type",
            new_name="_old_type",
        ),
        # 4. Add new FK field (nullable first, because existing rows have no FK yet)
        migrations.AddField(
            model_name="account",
            name="account_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="finance.accounttype",
                verbose_name="账户类型",
            ),
        ),
        # 5. Map old string values to AccountType FKs
        migrations.RunPython(map_account_types, reverse_code=migrations.RunPython.noop),
    ]
